### ISSUE TITLE
The html `<meta>` description and keywords is out of sync with package.json's

### ISSUE THREAD

**Issue by GrosSacASac** [GrosSacASac/DOM99#24]
The html files are already generated from `documentation/documentation-original.html`
and `documentation/index-original.html`

with
https://github.com/GrosSacASac/DOM99/blob/master/tools/buildHTML.js

Read from package.json description and keywords
use `.replace()` before this line
https://github.com/GrosSacASac/DOM99/blob/master/tools/buildHTML.js#L60

Replace something unique like DESCRIPTION placeholder.

**Comment by GrosSacASac** [comment]
description is there twice in `documentation/index-original.html`

**Comment by VigneshMurugan** [comment]
picking this up
