### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by GrosSacASac** [GrosSacASac/DOM99#5]
https://github.com/GrosSacASac/DOM99/blob/master/tests/specification/spec/dom99.js

Most of the features are not covered by tests, increase general test coverage

**Comment by VigneshMurugan** [comment]
Will work on this issue

**Comment by VigneshMurugan** [comment]
> Thanks, are you going to add more after #16 ?

Of course I am adding few more. Will complete everything and raise a single pull request

**Comment by GrosSacASac** [comment]
https://github.com/GrosSacASac/DOM99/commit/0673579701c32cb61931ccfdae0c9e76ea79ac3a

**Comment by GrosSacASac** [comment]
test coverage is 60%

**Comment by GrosSacASac** [comment]
68%
