### ISSUE TITLE
Fix link in the doc

### ISSUE THREAD

**Issue by GrosSacASac** [GrosSacASac/DOM99#64]
Production minified dom99Script.es5.min.js
should be Production minified dom99.iife.es5.min.js

**Comment by GrosSacASac** [comment]
blocked, must first release 21.0.0,
also use https://unpkg.com link

**Comment by wale-bant** [comment]
Hi, can i work on this?

**Comment by GrosSacASac** [comment]
It is blocked for now, I will release v21.0.0 during this week and then yes

**Comment by wale-bant** [comment]
Ok

**Comment by GrosSacASac** [comment]
the link should be https://unpkg.com/dom99/built/dom99.iife.es5.min.js
the text of the link should be dom99.iife.es5.min.js

**Comment by GrosSacASac** [comment]
thanks for you patience, we are waiting for your PR now :)

**Comment by wale-bant** [comment]
I'm on it.

**Comment by GrosSacASac** [comment]
ok
