### ISSUE TITLE
@babel/polyfill is deprecated since 7.4.0

### ISSUE THREAD

**Issue by MyIsaak** [GrosSacASac/DOM99#67]
https://github.com/GrosSacASac/DOM99/blob/bd2bf3d0be6d6a9a8e4138c2ec987419f5a682f9/package.json#L44

Problem: Using deprecated package. More info https://babeljs.io/docs/en/babel-polyfill

Proposed solution: Replace [all usage of @babel/polyfill in the repo](https://github.com/GrosSacASac/DOM99/search?q=babel%2Fpolyfill&unscoped_q=babel%2Fpolyfill) with:
`core-js/stable` and `regenerator-runtime/runtime`.

**Comment by GrosSacASac** [comment]
It is only used in the examples. I will change it eventually.
