### ISSUE TITLE
Git ignore generated files

### ISSUE THREAD

**Issue by GrosSacASac** [GrosSacASac/DOM99#9]
* To avoid confusion https://github.com/GrosSacASac/DOM99/pull/6 https://github.com/GrosSacASac/DOM99/pull/8
 * To remove noise in the commits
 
Make sure generated files are still included in `npm publish` and documentation files are included before publishing site to now.
Make a commit to delete these files first.

To ignore:
 * everything in built/ 
 * documentation/documentation.html
 * documentation/index.html
 * documentation/global.html
 * documentation/dom99.js.html
 * documentation/js/documentation.es5.min.js
 * examples/js/built
 * examples/js/builtes5
 * components/yesNoDialog/examples/js/built

**Comment by jfstn** [comment]
I'll take care of this
